# Generated by Django 4.1.7 on 2023-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(help_text='Текст длиной до 500 символов', verbose_name='Описание вашего фильма'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(help_text='Текст длиной до 500 символов', verbose_name='Название фильма'),
        ),
    ]
