# Generated by Django 4.1.7 on 2023-03-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_post_image_alter_post_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
